<section>
	<article>
		<h2>Nous contacter</h2>

		<a href="https://goo.gl/maps/sJUk9HLxU1cjxAP3A"><img src="img/map.jpg" alt="Le plan pour trouver le DOJO" class="shadow"></a>
		<p>Pour vous inscrire ou pour tout renseignement, merci de téléphoner au 06 60 26 07 84 , d'envoyer un message FB ou un courriel à stephan.talbot@gmail.com.</p>

		<p>Vous pouvez aussi directement vous rendre au dojo d'Aïkido, au 24 rue de la Tizardière à Selles-sur-Cher aux horaires des cours.</p>

		<p class="clear">Cours d'essai possible sans engagement.</p>

		<h3>Pratiquer l'Aïkido</h3>
		<p class="shedules">Aïkido enfants : Mercredi de 17h00  à 18h00</p>
		<p class="shedules">Aïkido adultes : Lundi de 19h30  à 21h00</p>

		<h3>Pratiquer Qi Gong</h3>

		<p>Tenue pour pratiquer : Tenue souple et confortable. T-shirt et survêtement sont parfaits. Si pratique régulière, prévoir chaussures réservées à une pratique en salle.</p>

		<p class="shedules">Atelier de Qi Gong : Mercredi  de 19h30 à 20h45</p>

		<p class="shedules">Atelier de Présence Méditative : Mercredi de 18h15 à 19h15</p>

	</article>
</section>
