<section>
	<article>
		<h2>Qu'est-ce que l'Aïkido ?</h2>

		<img src="img/aikido.jpg" alt="Photo de la prise en Aïkido">
		<p><i>« La voie du Guerrier est basée sur l’humanité, l’amour et la sincérité, le cœur de la valeur martiale est la vraie bravoure, la sagesse, l’amour et l’amitié. Insister sur les aspects physiques de l’état du guerrier n’est que futilité, car le pouvoir du corps est toujours limité. »</i> - Morihei Ueshiba</p>

		<p>L'aïkido est un art martial japonais fondé par Morihei Ueshiba. Il est accessible à tous quelque soit son âge, sexe ou condition physique et se pratique sans violence.</p>

		<p>Il est né des techniques de combat des guerriers japonais, les bujutsu.</p>

		<p>Mais, l'aïkido est avant tout un budō. Une signification littérale du mot budō est " La voie pour arrêter la lance". La syllabe bu signifie le combat et l'objectif d'un bujutsu est de gagner le combat. En revanche, un budō porte à une autre dimension, et la pratique devient un chemin de vie.</p>

		<h2 class="clear">L'enseignement "traditionnel"</h2>

		<img src="img/aikido-mouvement.jpg" alt="Photo de la projection en Aïkido">

		<p>Un enseignement traditionnel tel qu'il est pratiqué à Selles-sur-Cher ou dans le cadre de notre école l' EPA ne fait pas référence à un folklore japonais.</p>

		<p>Le terme traditionnel renvoie plutôt à des principes universels. Cette pratique de l'Aïkido Traditionnel se fait dans certaines conditions, certains lieux et en respectant certains principes. Et c'est le respect de cet ensemble de valeurs qui permet à chaque pratiquant d'étudier et de progresser dans cette voie qu'il a choisie auprès du maître qu'il s'est choisi.</p>
	</article>
</section>
