<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Page d'erreur</title>
    <meta name="viewport" content = "width=device-width, initial-scale=1.0">
    <meta charset ="utf-8">
    <meta name="description" content="L’Aïkido - UNE DISCIPLINE, UNE PHILOSOPHIE, UN ART." />
    <meta name="robots" content="noindex,nofollow" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
  </head>
  <body>
    <section>
      <h1>Il semble que cette page n'existe pas</h1>
        <img src="img/estamp.png" alt="dessin du soleil et du sakura japonaise">
    </section>
  </body>
</html>
