	</main>
	</div>
	<footer>
		<h3>Pratiquer l'Aïkido</h3>
		<ul>
			<li><i class="fa fa-envelope"></i>: stephan.talbot@gmail.com</li><!--
			--><li><i class="fa fa-mobile"></i>: 06 60 26 07 84</li>
		</ul>
	</footer>
	<div id="goUp" class="none">
		<a href="#menu"><i class="fas fa-chevron-circle-up" id = "buttonUp"></i></a>
	</div>
	<script type="text/javascript" src="js/goUp.js"></script>
</body>
</html>
