<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Aikido-Styles : <?=$pTitle; ?></title>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	<meta charset ="utf-8">
	<meta name="description" content="Qi Gong, Méditation, Aïkido… Allez à la rencontre de votre Essentiel." />
	<meta name="robots" content="noindex,nofollow" >
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
 <div id="conteineur">
	<header>
		<div>
			<h1>Dojo Selle sur Chere</h1>
			<h2>Dojo de l'Instant Présent</h2>
		</div>
	</header>
	<nav>
			<ul id="menu">
				<li><a href="index.php?page=titre-1" title="titre-1">Aikido</a></li><!--
				--><li><a href="index.php?page=titre-2" title="titre-2">Titre-2</a></li><!--
				--><li><a href="index.php?page=titre-3" title="titre-3">Titre-3</a></li><!--
				--><li><a href="index.php?page=titre-4" title="titre-4">Titre-4</a></li><!--
				--><li><a href="index.php?page=titre-5" title="titre-5">Titre-5</a></li>
			</ul>
	</nav>
