<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Dojo de l'Instant Présent : <?=$page ?></title>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	<meta charset ="utf-8">
	<meta name="description" content="Qi Gong, Méditation, Aïkido… Allez à la rencontre de votre Essentiel." />
	<meta name="robots" content="noindex,nofollow" >
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
 <div id="conteineur">
	<header>
		<div>
			<h1>Dojo Selles sur Cher</h1>
			<h2>Dojo de l'Instant Présent</h2>
		</div>
	</header>
	<nav>
			<ul id="menu">
				  <?php print_nav($headings); ?>
			</ul>
	</nav>
	<main>
