<?php $pTitle = 'Aikido'; ?>
<?php include 'header.phtml'; ?>

<main id="presantation">
		<section>
			<h1>Ex nulla oblique sit</h1>
			<article>
				<h2>Ex nulla oblique sit</h2>
				<p>Ex nulla oblique sit, quo no vide ponderum ocurreret. Ne elit inani quo. Officiis reprehendunt ad cum, ei aliquam placerat eum. Justo summo lucilius ne has, no nec adipiscing consectetuer.</p>
				<p>Ex nulla oblique sit, quo no vide ponderum ocurreret. Ne elit inani quo. Officiis reprehendunt ad cum, ei aliquam placerat eum. Justo summo lucilius ne has, no nec adipiscing consectetuer.</p>
				<ul>
					<li>No nec adipiscing</li>
					<li>Quo no vide</li>
					<li>Ne elit inani quo</li>
				</ul>
				<p>Ex nulla oblique sit, quo no vide ponderum ocurreret. Ne elit inani quo. Officiis reprehendunt ad cum, ei aliquam placerat eum. Justo summo lucilius ne has, no nec adipiscing consectetuer.</p>
			</article>
		</section>
	</main>

<?php include 'footer.phtml'; ?>
