<section>
	<article>
		<h2>Quelques principes de l'Aïkido Traditionnel</h2>

		<ul>
			<li>Un lieu : Le dojo traditionnel</li>
			<li>Un principe : Un maître - Un dojo</li>
		</ul>

		<p>Littéralement, dojo signifie « lieu où l'on étudie la voie ». Le dojo traditionnel ne doit pas être vu comme une salle de sport dans laquelle le pratiquant vient faire une activité physique, prend sa douche et ressort jusqu'au prochain cours.</p>

		<img src="img/aikido-enfants.jpg" alt="Photo des enfants en train de pratiquer l'Aïkido">

		<p>Le dojo traditionnel, tel qu'il est perçu dans notre école l'EPA, est associé à un professeur. Un professeur crée son dojo, en ayant l'autorisation préalable de son propre professeur. Dans ce dojo, il accepte ses élèves et leur dispense son enseignement.</p>

		<p>Dans ce dojo, à travers le cadre, l'étiquette, les élèves progressent dans leur perception de l'Aïkido. À travers son enseignement, le maître ( c'est à dire le professeur ), en mettant les élèves en condition d'apprentissage, progresse lui-aussi dans son propre Aïkido.</p>

		<p class="clear">Le dojo symbolise le champ de bataille. Chaque chose, chaque personne doit donc être située à sa juste place. Lors du salut, les élèves sont installés dans l'ordre de leur ancienneté, les plus anciens en face à gauche du professeur et les débutants tout à fait à droite.</p>

		<p>Les armes doivent être sorties, prêtes à être utilisées.</p>
		<img src="img/aikido-eleve.jpg" alt="Photo de l'explication d'un prise d'Aïkido">
		<p>Chaque élève a un rôle à jouer. À charge des plus anciens de s'occuper des débutants, de leur expliquer le fonctionnement du dojo, du cours, comment s'habiller ou se comporter sur un tatami. Tel élève balaie le tatami avant le cours, tel autre sort les armes et les installe correctement, le tout, avec l'aide d'un plus ancien ( un sempai ).</p>

		<p>Un élève d'Aïkido Traditionnel n'est pas un consommateur d'Aïkido.</p>

		<p>Pratiquer le budō qu'est l'Aïkido demande une implication dans le fonctionnement du dojo. Cet investissement permettra à chacun de mettre en pratique et de compléter ce qu'il apprend sur le tatami.</p>

		<p class="clear">Lorsque le professeur décide qu'un élève a acquis suffisamment d'expérience, il peut alors lui confier une tâche dans la gestion du dojo : la comptabilité, le secrétariat ...</p>

		<p>L'élève devient alors un uchi-deshi.</p>

		<p>Avec la réalisation de cette tâche, il travaille en vue d'acquérir davantage d'autonomie, avec toujours comme objectif de mettre en pratique dans la vie extérieure ce qui est enseigné sur le tatami.</p>

		<p>Il pourra peut-être alors compléter son apprentissage en devenant à son tour professeur et ouvrir son propre dojo.</p>
	</article>
</section>
