<section>
	<article>
		<h2>Bien-être, Santé et Harmonie intérieure avec le Qi Gong</h2>

		<p>Le Qi Gong est un art de santé, de bien-être et de réalisation de Soi.</p>

		<p>Il est souvent présenté en occident comme une gymnastique énergétique de santé. C'est une pratique douce qui s'adapte à tous et à tous les âges et qui vise à l'épanouissement personnel et au bien-être, à l'entretien de la santé et à l'harmonie intérieure.</p>

		<p>Alliant mouvements souples, douce concentration de l'esprit et respiration, il permet de mieux faire circuler, ce que les Chinois appellent le Qi.  On peut dire pour faire simple que le Qi est le Souffle, l'énergie de Vie qui anime tout être vivant.</p>

		<p>Lorsque votre Souffle/énergie de Vie est bloqué, cela créé des désordres internes qui finissent par créer toutes sortes de mal-être, de douleurs et qui peuvent finir par aboutir à la maladie.</p>

		<p>Malheureusement, notre mode de vie actuel favorise beaucoup ces blocages du Souffle/énergie de Vie.</p>

		<p>Heureusement, une pratique régulière du Qi Gong vous permettra graduellement de libérer ces blocages... et de refaire circuler abondamment et harmonieusement ce Qi de Vie dans votre corps... pour votre plus grand bien-être.</p>

		<p>En règle générale, une pratique régulière du Qi Gong amène :</p>

		<ul>
			<li>un renforcement du corps lui faisant retrouver plus de souplesse au niveau musculaire et articulaire</li>
			<li>un regain de vitalité et d'énergie</li>
			<li>développe et entretient une bonne capacité respiratoire</li>
			<li>optimise toutes les fonctions de votre organisme</li>
			<li>aide à éliminer les tensions nerveuses, amène à plus de calme mental</li>
			<li>une meilleure gestion de vos émotions</li>
			<li>renforce et stimule votre système immunitaire</li>
			<li>un bien-être physique et mental accru, une plus grande harmonie intérieure</li>
			<li>une plus grande résistance au stress</li>
			<li>développe votre équilibre</li>
			<li>favorise l'éclosion de la créativité</li>
			<li>permet de retrouver une bonne faculté de concentration (si souvent perdue actuellement)</li>
			<li>prolonge la vie en l'améliorant</li>
			<li>et bien d'autres choses merveilleuses encore que vous découvrirez par la pratique...</li>
		</ul>

		<p>Vous aussi expérimentez les bienfaits d'un pratique régulière du Qi Gong !</p>
	</article>
</section>
