<section>
	<article>
		<h2>La relation Sempai-Kōhai</h2>

		<p>Lorsqu'un élève entre dans un dojo, il devient le kōhai d'un élève plus ancien qui devient alors son sempai.</p>

		<p>Un pratiquant d'Aïkido traditionnel est donc toujours, quelque soit son ancienneté et son expérience, le kōhai d'un autre et le sempai d'un élève qui est plus débutant que lui.</p>

		<p>Le rôle de sempai est un rôle important. On perçoit ceci à travers la double signification du verbe « apprendre »</p>

		<p>Apprendre, c'est donner un enseignement mais aussi recevoir un enseignement.</p>

		<p>En transmettant ses connaissances à son kōhai, en lui expliquant le fonctionnement du dojo, en le conseillant sur telle ou telle technique, ou telle attitude, le sempai consolide ses connaissances et progresse dans son Aïkido.</p>

		<p>Enseigner permet de réfléchir sur sa pratique, de faire le point sur son Aïkido, sur son évolution, et permet d'aller plus loin.</p>

		<p>Cette transmission se fait en toute humilité car on apprend toujours d'un plus débutant. De plus, cette transmission se faisant dans le dojo du professeur et elle doit être la plus fidèle possible à son enseignement. Un élève ne peut donc prendre le prétexte de son ancienneté ou de son expérience pour s'auto-proclamer professeur et donner des conseils en contradiction avec l'enseignant.</p>
	</article>
</section>
