<?php $pTitle = 'Titre 1'; ?>
<?php include 'header.phtml'; ?>

<main id="developpement">
		<section>
			<h1>L'Aïkido Yoshinkan</h1>
			<article>
				<h2>Lorem ipsum dolor sit amet</h2>
				<p>Lorem ipsum dolor sit amet<strong>Aïkido</strong> Lorem ipsum dolor sit amet :</p>
				<h3>Lorem ipsum dolor sit amet :</h3>
				<ul class="left">
					<li>Lorem ipsum dolor sit amet</li>
					<li>Lorem ipsum dolor sit amet, velit tincidunt interpretaris in nam, quaestio eloquentiam</li>
					<li>Lorem ipsum dolor sit amet, velit tincidunt interpretaris in nam</li>
					<li>Lorem ipsum </li>
					<li>Lorem </li>
				</ul>

				<h3>Lorem ipsum dolor sit amet</h3>
				<ul class="left">
					<li>Lorem ipsum dolor sit amet</li>
					<li>Velit tincidunt interpretaris in nam, quaestio eloquentiam</li>
					<li>velit tincidunt interpretaris in nam</li>
				</ul>

				<h3>Velit tincidunt interpretaris in nam, quaestio eloquentiam :</h3>
				<p>Lorem ipsum dolor sit amet, velit tincidunt interpretaris in nam, quaestio eloquentiam quo id, sint partiendo no sed. Malorum corrumpit no pri, invenire atomorum mel cu. Ea commune adolescens usu, nec minim argumentum no. Erat latine erroribus ex mei, te mea dicat evertitur. No harum diceret sed. Omnesque constituto vix ex.</p>
				<p>Sit amet <strong>Bushido</strong>, sit amet<strong>Aïkido</strong>, Odio dico liber sit an. Id scripta veritus persecuti vis. Tempor placerat periculis per te, vel ne oratio euismod :</p>

				<ul>
					<li>Interpretaris</li>
					<li>Quaestio</li>
					<li>Guaestio</li>
					<li>Velit</li>
					<li>Tincidunt</li>
					<li>Odio</li>
					<li>Liber</li>
					<li>Id scripta veritus</li>
				</ul>

			</article>
			<article>
				<h2>Has ei vidit</h2>
				<p>Ex nulla oblique sit, quo no vide ponderum ocurreret. Ne elit inani quo. Officiis reprehendunt ad cum, ei aliquam placerat eum. Justo summo lucilius ne has, no nec adipiscing consectetuer.</p>
				<p>Ei solum eruditi saperet nam, sit choro option accumsan no. Has ei vidit libris nonumes. Ne purto facilisi efficiantur pro. Per liber complectitur interpretaris ne, nulla propriae no ius, zril neglegentur vix no. Hinc doctus apeirian ex per.</p>
			</article>
		</section>
	</main>

<?php include 'footer.phtml'; ?>
