<?php $pTitle = 'Titre-2'; ?>
<?php include 'header.phtml'; ?>

<main id="origine">
		<section>
			<h1>Ponderum ocurreret</h1>
			<article>
				<h2>Ponderum ocurreret</h2>
				<p>Ex nulla oblique sit, quo no vide ponderum ocurreret. Ne elit inani quo. Officiis reprehendunt ad cum, ei aliquam placerat eum. Justo summo lucilius ne has, no nec adipiscing consectetuer.</p>
				<p>Ex nulla oblique sit, quo no vide ponderum ocurreret. Ne elit inani quo. Officiis reprehendunt ad cum, ei aliquam placerat eum. Justo summo lucilius ne has, no nec adipiscing consectetuer.</p>
			</article>
		</section>
	</main>

<?php include 'footer.phtml'; ?>
