<?php $pTitle = 'Cours où et quand'; ?>
<?php include 'header.phtml'; ?>

<main id="cours">
		<section>
			<h1>Cours - où et quand?</h1>
			<article>
				<h2>L'Adresse :</h2>
				<ul>
					<li>Centre Omnisport</li>
					<li>35830 Betton</li>
				</ul>

				<div id="maps">
					<iframe src="https://www.google.com/maps/embed?pb" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
				</div>

				<h2>Les horaires :</h2>
				<ul>
					<li>Section Jeunes (8 à 14 ans) : mardi 18h30 à 19h30</li>
					<li>Section Adulte : mardi et vendredi 19h30 à 22h00</li>
				</ul>
			</article>
		</section>
	</main>
<?php include 'footer.phtml'; ?>
